# AWS S3 / Supabase Storage
spring:
  cloud:
    aws:
      region:
        #        static: ${AWS_REGION} # ì˜ˆ: ap-northeast-2
        static: ${REGION}
      credentials:
        #        access-key: ${AWS_ACCESS_KEY}
        #        secret-key: ${AWS_SECRET_KEY}
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      s3:
        #        bucket: ${AWS_S3_BUCKET_NAME}
        bucket: ${S3_BUCKET_NAME}
        # í•„ìš”í•  ê²½ìš° endpoint ì‚¬ìš©
        # endpoint: ${AWS_S3_ENDPOINT_URL}
        # path-style-access-enabled: true
      cloudfront:
        domain: ${CLOUDFRONT_DOMAIN}

  # Kakao OAuth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            # client-secret: ${KAKAO_CLIENT_SECRET} # Client Secretì„ ì‚¬ìš©í•˜ëŠ” ê²½ìš° ì£¼ì„ í•´ì œ
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      #username: ${REDIS_USERNAME}
      #password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
      timeout: 5000ms  # ì—°ê²° íƒ€ì„ì•„ì›ƒ 5ì´ˆ
      lettuce:
        pool:
          max-active: 8   # ìµœëŒ€ í™œì„± ì—°ê²° ìˆ˜
          max-idle: 8     # ìµœëŒ€ ìœ íœ´ ì—°ê²° ìˆ˜
          min-idle: 2     # ìµœì†Œ ìœ íœ´ ì—°ê²° ìˆ˜
          max-wait: 3000ms  # ì—°ê²° ëŒ€ê¸° ì‹œê°„

  # Database (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA
  jpa:
    hibernate:
      # ddl-auto: update
      ddl-auto: validate # ê°œë°œ ì´ˆê¸° ë‹¨ê³„ì—ì„œëŠ” update ë˜ëŠ” create, ìš´ì˜ì—ì„œëŠ” validate ë˜ëŠ” none ì‚¬ìš©

# AWS S3 Bucket
#aws:
#  s3:
#    bucket: ${AWS_S3_BUCKET_NAME}

# JWT
jwt:
  secret: ${JWT_SECRET}
  expiry:
    access: 3600000  # 1ì‹œê°„ (ë°€ë¦¬ì´ˆ) // ğŸ“Œ ë¡œê·¸ì¸ ì‹œê°„ ëŠ˜ë ¸ì–´ìš”~~
    refresh: 604800000  # 7ì¼