# AWS S3 / Supabase Storage
spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION} # 예: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
        # 필요할 경우 endpoint 사용
        # endpoint: ${AWS_S3_ENDPOINT_URL}
        # path-style-access-enabled: true

  # Kakao OAuth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            # client-secret: ${KAKAO_CLIENT_SECRET} # Client Secret을 사용하는 경우 주석 해제
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
      ssl:
        enabled: true

  # Database (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate # 개발 초기 단계에서는 update 또는 create, 운영에서는 validate 또는 none 사용

# AWS S3 Bucket
#aws:
#  s3:
#    bucket: ${AWS_S3_BUCKET_NAME}

# JWT
jwt:
  secret: ${JWT_SECRET}
  expiry:
    access: 60000      # 1분
    refresh: 3600000 # 1시간